apiVersion: v1
kind: ConfigMap
metadata:
  name: netbox-config
  namespace: example
data:
  # NetBox environment variables
  # More configuration can be added via: https://netbox.readthedocs.io/en/stable/configuration/optional-settings/
  ENFORCE_GLOBAL_UNIQUE: "True"
  ALLOWED_HOSTS: '*'
  CHANGELOG_RETENTION: "90"
  DB_HOST: db-example-namespace.svc.cluster.local
  DB_NAME: netbox
  DB_USER: somedbuser
  EMAIL_FROM: netbox@bar.com
  EMAIL_PORT: "25"
  EMAIL_SERVER: localhost
  EMAIL_TIMEOUT: "10"
  EMAIL_USERNAME: foo
  EXEMPT_VIEW_PERMISSIONS: ''
  LOGIN_REQUIRED: "true"
  MEDIA_ROOT: ''
  METRICS_ENABLED: "true"
  NETBOX_USERNAME: guest
  REDIS_HOST: redis-example-namespace.svc.cluster.local
  REDIS_CACHE_HOST: redis-example-namespace.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_CACHE_PORT: "6379"
  REDIS_DATABASE: "0"
  REDIS_CACHE_DATABASE: "1"
  SUPERUSER_EMAIL: admin@example.com
  SUPERUSER_NAME: admin
  MAINTENANCE_MODE: 'False'
  DEBUG: 'False'
  REMOTE_AUTH_ENABLED: 'True'
  REMOTE_AUTH_AUTO_CREATE_USER: 'True'
  REMOTE_AUTH_BACKEND: 'django3_saml2_nbplugin.backends.SAML2CustomAttrUserBackend'
  REMOTE_AUTH_HEADER: "HTTP_REMOTE_USER"
  BANNER_LOGIN: '<a href="/api/plugins/sso/login" class="btn btn-primary btn-block">Login with SSO</a>'