apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-netbox-topology-views
  namespace: example
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10G